# --- CASEC parameters ---
name: "casec"

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
action_encoder: "obs_reward"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 70000
epsilon_anneal_time_exp: 70000
evaluation_epsilon: 0.0

runner: "episode"
buffer_size: 5000
target_update_interval: 200

# Specify the gnn_marl
threshold: 0.3
individual_dim: 16
delta_dim: 64

# specify learner, controller and agent
agent: "casec_rnn"
pair_agent: "pair_rnn"
agent_output_type: "q"
learner: "casec_learner"
mac: "casec_mac"
mixer: "vdn"
double_q: True
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
p_lr: 1.0

rnn_hidden_dim: 64
pair_rnn_hidden_dim: 128
independent_p_q: False
edge_threshold_start: 0.00001
edge_threshold_end: 0.01
edge_threshold_increasing_time: 500000

# Sparseness learning loss
l1_loss_weight: 0.00001
q_var_loss_weight: 0.0001
delta_var_loss_weight: 0.0001
l1_loss: False
q_var_loss: False
delta_var_loss: False
no_loss: False

use_action_repr: False
action_latent_dim: 20
state_latent_dim: 32
action_repr_learning_phase: 50000

atten_dim: 32

# How to construct adjacency graph
construction_delta_var: False
construction_q_var: False
construction_delta_abs: False
construction_history_similarity: False
construction_attention: False
random_graph: False
full_graph: False

obs_agent_id: True
obs_last_action: True
obs_individual_obs: False
