# --- DGN specific parameters ---
name: "dgn"

# Exploration
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "episode"
buffer_size: 5000

# Agent inputs
obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# DGN architecture
dgn_embed_dim: 128
dgn_encoder_hidden: [128, 128]
dgn_n_heads: 8

# Training
standardise_returns: False
standardise_rewards: True
target_update_interval_or_tau: 200
double_q: True

agent_output_type: "q"
learner: "q_learner"
mac: "dgn_mac"
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
