# --- GTCG specific parameters ---
name: "gtcg"
is_masssge: True

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval_or_tau: 200

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# GTCG graph
train_graph: False
dicg_emb_hid: 128
number_gcn_layers: 2
residual: True
transformer_heads: 1
use_attention_module: False
gtcg_conv_type: "transf"
param_match: False
run_tag: ""

# use the Q_Learner to train / QMIX as baseline
standardise_returns: False
standardise_rewards: True

agent_output_type: "q"
learner: "q_learner"
mac: "gtcg_mac"
double_q: True
mixer: "qmix"
use_rnn: False
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
