# --- LTSCG specific parameters ---
name: "ltscg"

# Exploration
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "episode"
buffer_size: 5000
target_update_interval_or_tau: 200

# Agent inputs
obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# LTSCG controller
dicg_emb_hid: 128
concate_mlp_dim: 10
gcn_message_dim: 10
number_gcn_layers: 2
concate_gcn: True
concate_mlp: True

# LTSCG learner
graph_loss_weight: 1.0
graph_emb_hid: 128
mlp_emb_hid: 64
mlp_out: 32
gtsmodel:
  cl_decay_steps: 2000
  filter_type: dual_random_walk
  horizon: 12
  input_dim: 2
  l1_decay: 0
  max_diffusion_step: 3
  num_nodes: 207
  num_rnn_layers: 1
  output_dim: 1
  rnn_units: 64
  seq_len: 12
  use_curriculum_learning: true
  dim_fc: 383552

# Training
standardise_returns: False
standardise_rewards: True
double_q: True

agent_output_type: "q"
learner: "ltscg_learner"
mac: "ltscg_mac"
mixer: "qmix"
use_rnn: False
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
